config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get 'home/about' => 'homes#about'
  resources :users, only: [:index, :show, :edit, :update] 
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  # has_one_attached :image
  #has_many_attached :profile_image
  belongs_to :user

  # def get_image
  #   if image.attached?
  #     image
  #   else
  #     'no_image.jpg'
  #   end
  # end
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  
end

app/models/post_image.rb
class PostImage < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    validates :name, uniqueness: true
    validates :name, presence: true, length: { minimum: 2, maximum: 20 }
    validates :introduction, length: { maximum: 50 }

  has_one_attached :profile_image
  has_many :books, dependent: :destroy

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: 'Book was successfully created.'
    else
      @books = Book.all
      @user = User.find(current_user.id)
      render 'index'
    end
  end

  def index
    @books = Book.all 
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
        render "edit"
    else
        redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
        redirect_to book_path(@book), notice: 'You have updated book successfully.'
    else
        render "edit"
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

end

private

  def book_params
        params.require(:book).permit(:title, :body)
  end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
        render "edit"
    else
        redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    @user.id = current_user.id
    if @user.update(user_params)
         redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else

      render "edit"
    end
  end
end

private

def user_params
  params.require(:user).permit(:profile_image, :name, :introduction)

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_newbook.html.erb
<h2 class= "mt-3">New book</h2>
<%= form_with model:book do |f| %>
<div class="form-group">
<%= f.label :Title %>
<%= f.text_field :title, class:"form-control" %>
</div>

<div class="form-group">
<%= f.label :Opinion %>
<%= f.text_area :body, class:"form-control" %>
</div>

<div class="form-group">
<%= f.submit class: "btn btn-success" %>
</div>
<% end %>

app/views/books/edit.html.erb
<%= form_with model: @book do |f| %>
<div class="container">

<% if @book.errors.any? %>
  <h2><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  <h1>Editing Book</h1>
  <div class="form-group">
    <label for="inputName">Title</label>
    <%= f.text_field :title, class:"form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :Opinion %>
    <%= f.text_area :body, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit "Update Book", class: "btn btn-success" %>
  </div>
  <div class="link">
    <%= link_to "Show", book_path(@book.id) %>
    <%= "  |  " %>
    <%= link_to "Back", books_path %>
  </div>
  </div>
 </div>
</div>

<% end %>

app/views/books/index.html.erb
<div class="container ">

<% if @book.errors.any? %>
  <h2><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user:@user %>
      <%= render 'books/newbook', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user.id) do %>
                <%= image_tag book.user.get_profile_image(50,50) %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class="container ">
  <p id="notice">
    <%= notice %>
  </p>
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user:@user %>
      <%= render 'books/newbook', book: @book_new %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user) do %>
                <%= image_tag @user.get_profile_image(100,100) %>
                <%= @user.name %>
              <% end %>
            </td>
            <td><%= @book.title %></td>
            <td><%= @book.body %></td>
            <% if user_signed_in? && current_user.id == @book.user_id %>
            <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-success btn-sm" %></td>
            <td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に消しますか？"}, class: "btn btn-danger btn-sm" %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h1>welcome to
      <i class="fas fa-book"></i>
      <strong>Bookers</strong>
      !!</h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <p id="notice">
    <%= notice %>
  </p>

  <div class="row">
    <div class="mx-auto">
      <h1>welcome to
      <span class="fas fa-book"></span>
      <span class="font-weight-bold">Bookers!!</span>
      </h1>
      <p>
        In
        <span class="fas fa-book"></span>
        <strong>Bookers</strong>,
      </p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>

      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-block btn-sm mb-3 sign_in" %>
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-block btn-sm mb-3 sign_in" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="fontawesome-i2svg-active fontawesome-i2svg-complete">
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/b1267ac2cc.js" crossorigin="anonymous"></script>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-dark bg-dark navbar-expand-lg">
      <div class="container">
      		<%= link_to "Bookers", root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
    <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to user_path(current_user), class: "nav-link text-light" do %>
        <i class="fas fa-home"></i>
          Home
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to users_path, class: "nav-link text-light" do %>
        <i class="fas fa-users"></i>
          Users
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to books_path, class: "nav-link text-light" do %>
        <i class="fas fa-book-open"></i>
          Books
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
        <i class="fas fa-sign-out-alt"></i>
          Log out
        <% end %>
      </li>

    <% else %>
      <li class="nav-item">
        <%= link_to root_path, class: "nav-link text-light" do %>
        <i class="fas fa-home"></i>
         Home
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to home_about_path, class: "nav-link text-light" do %>
        <i class="fas fa-link"></i>
         About
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
        <i class="fas fa-user-plus"></i>
          Sign up
        <% end %>
      </li>
      <li class="nav-item">
      <%= link_to user_session_path, class: "nav-link text-light" do %>
      <i class="fas fa-sign-in-alt"></i>
        Log in
      <% end %>
      </li>
    <% end %>
    </ul>
    <!--<p class="navbar-text">welcome to Bookers!!</p>-->
    </div>
    </div>
  </nav>
</header>
    <%= yield %>


  <footer>
    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>
 </body>
</html>

app/views/users/_user.html.erb
<table class="table">
  <h2>User info</h2>
    <thead>
      <%= image_tag user.get_profile_image(100,100) %>
    </thead>

    <tr>
      <th>Name</th>
      <th><%= user.name %></th>
    </tr>

    <th>Introduction</th>
      <th><%= user.introduction %></th>
    </tr>

</table>

  <div class="row">
      <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
      <% end %>
  </div>

app/views/users/edit.html.erb
<p id="notice">
  <%= notice %>
</p>

  <% if @user.errors.any? %>
      <h2><%= @user.errors.count %> errors prohibited this book from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  <% end %>

<%= form_with model: @user do |f| %>
<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  <h2>User info</h2>
  <div class="form-group">
    <label for="inputName">Name</label>
    <%= f.text_field :name, class:"form-control"%>
  </div>

  <div class="form-group">
    <label for="inputImage">Image</label>
    <%= f.file_field :profile_image, class:"form-control-file" %>
  </div>

  <div class="form-group">
    <%= f.label :introduction %>
    <%= f.text_area :introduction, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit "Update User" %>
  </div>
  </div>
 </div>
</div>

<% end %>

app/views/users/index.html.erb
<div class="container ">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user: @user %>
      <%= render 'books/newbook', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td>
                <%= image_tag @user.get_profile_image(80,80) %>
            </td>
            <td><%= user.name %></td>
            <td><%= link_to "Show",user_path(user.id), class: "btn btn-secondary" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container ">
  <p id="notice">
    <%= notice %>
  </p>
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user: @user %>
      <%= render 'books/newbook', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user.id) do %>
                <%= image_tag book.user.get_profile_image(80,80) %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>